server:
  port: 10110
  servlet:
    context-path: /workbin

spring:
  profiles:
    active: test
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/
  mvc:
    static-path-pattern: /**
    view:
      prefix: /
      suffix: .html
#  http:
#    encoding:
#      enabled: true
#      charset: UTF-8
#      force: true

#  redis:
#    databases:
#      shiro: 0
#      business: 1
#    host: 192.168.1.11
#    port: 6379
#    # timeout属性，单位： 毫秒
#    timeout: 3000
#    password:
#    jedis:
#      pool:
#        max-active: 100
#        max-idle: 20
#        min-idle: 2
#        # max-wait属性，单位： 毫秒
#        max-wait: 10000

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
mybatis:
  mapper-locations: classpath*:mapper/*/*.xml
  configuration:
    # 配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mybatis-plus:
    mapper-locations: classpath*:mybatis-config/mybatis-config.xml