spring:
  datasource:
    name: wms
    username: root
    password: '1234'
    url: jdbc:mysql://localhost:3306/wms_demo?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 配置rabbitMQspring:
  rabbitmq:
    host: 52.83.193.245
    username: wms-test
    password: wms-test

netty:
  port: 10111

wcs:
  token: eyJraWQiOiJhcHBUb2tlbiIsInR5cCI6IkpXVCIsImFsZyI6IkhTMjU2In0.eyJhdWQiOiI1ZjM2NTRkZGE5NTExZTAwMDE3ZTc0MTYifQ.csHUC39T2ZQWRAIebHjNTtXb975qsVhgQuylcnTy-7k
  sectionId: 11
  updateBinUrl: http://tote-wcs-api.mushiny.local/tote/factory/updateBin #修改货位料箱
  callToteUrl: http://tote-wcs-api.mushiny.local/tote/factory/tote-call #料箱呼叫
  queryBinListUrl: http://tote-wcs-api.mushiny.local/tote/rake/bin/queryBinList #货位料箱信息查询