spring:
  datasource:
    name: wms
    username: root
    password: '1234'
    url: jdbc:mysql://localhost:3306/wms_demo?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 配置rabbitMQspring:
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest

netty:
  port: 10111